// DNS Inspector
// Copyright (C) Ian Spence and other DNS Inspector Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE DIRECTLY!
// This file is generated automatically using the lang.py script located in
// the same directory as this file

import Foundation

public enum SupportedLanguages: String, Sendable, Hashable, Identifiable, CaseIterable, Codable {
    case English = "en"
    case Spanish = "es"
    case German = "de"
    case Polish = "pl"

    public var id: Self {
        return self
    }
}

@MainActor
public var currentLanguage: SupportedLanguages = .English

@MainActor
public final class Localize {
    // key: About
    public static func about() -> String {
        switch currentLanguage {
        case .English:
            return "About"
        case .Spanish:
            return "Acerca de"
        case .German:
            return "Über"
        case .Polish:
            return "O aplikacji"
        }
    }
    // key: Absolute
    public static func absolute() -> String {
        switch currentLanguage {
        case .English:
            return "Absolute"
        case .Spanish:
            return "Absoluto"
        case .German:
            return "Absolut"
        case .Polish:
            return "Bezwzględne"
        }
    }
    // key: Add Saved Server
    public static func addsavedserver() -> String {
        switch currentLanguage {
        case .English:
            return "Add Saved Server"
        case .Spanish:
            return "Add Saved Server"
        case .German:
            return "Add Saved Server"
        case .Polish:
            return "Dodaj zapisany serwer"
        }
    }
    // key: Administrative address
    public static func administrativeaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Administrative address"
        case .Spanish:
            return "Administrative address"
        case .German:
            return "Administrative Adresse"
        case .Polish:
            return "Adres administracyjny"
        }
    }
    // key: Algorithm
    public static func algorithm() -> String {
        switch currentLanguage {
        case .English:
            return "Algorithm"
        case .Spanish:
            return "Algorithm"
        case .German:
            return "Algorithmus"
        case .Polish:
            return "Algorytm"
        }
    }
    // key: Altitude
    public static func altitude() -> String {
        switch currentLanguage {
        case .English:
            return "Altitude"
        case .Spanish:
            return "Altitude"
        case .German:
            return "Altitude"
        case .Polish:
            return "Wysokość"
        }
    }
    // key: Answers
    public static func answers() -> String {
        switch currentLanguage {
        case .English:
            return "Answers"
        case .Spanish:
            return "Respuestas"
        case .German:
            return "Antworten"
        case .Polish:
            return "Odpowiedzi"
        }
    }
    // key: App Icon
    public static func appicon() -> String {
        switch currentLanguage {
        case .English:
            return "App Icon"
        case .Spanish:
            return "App Icon"
        case .German:
            return "App Icon"
        case .Polish:
            return "Ikona aplikacji"
        }
    }
    // key: App language
    public static func applanguage() -> String {
        switch currentLanguage {
        case .English:
            return "App language"
        case .Spanish:
            return "App language"
        case .German:
            return "App-Sprache"
        case .Polish:
            return "Język aplikacji"
        }
    }
    // key: AppIconFooter
    public static func appiconfooter() -> String {
        switch currentLanguage {
        case .English:
            return "The \"Progress\" pride flag was created by Daniel Quasar and is licensed under Create Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        case .Spanish:
            return "The \"Progress\" pride flag was created by Daniel Quasar and is licensed under Create Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        case .German:
            return "The \"Progress\" pride flag was created by Daniel Quasar and is licensed under Create Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        case .Polish:
            return "Flaga Pride została stworzona przez Daniela Quasara i jest licencjonowana na warunkach Creative Commons BY-NC-SA. Flaga Trans została stworzona przez Monicę Helms i udostępniona do domeny publicznej."
        }
    }
    // key: Appearance & Behaviour
    public static func appearancebehaviour() -> String {
        switch currentLanguage {
        case .English:
            return "Appearance & Behaviour"
        case .Spanish:
            return "Appearance & Behaviour"
        case .German:
            return "Aussehen & Verhalten"
        case .Polish:
            return "Wygląd i zachowanie"
        }
    }
    // key: Area
    public static func area() -> String {
        switch currentLanguage {
        case .English:
            return "Area"
        case .Spanish:
            return "Area"
        case .German:
            return "Area"
        case .Polish:
            return "Obszar"
        }
    }
    // key: Authority
    public static func authority() -> String {
        switch currentLanguage {
        case .English:
            return "Authority"
        case .Spanish:
            return "Authority"
        case .German:
            return "Authority"
        case .Polish:
            return "Autorytatywny"
        }
    }
    // key: Bad signing key: {details}
    public static func badsigningkeydetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Bad signing key: \(details)"
        case .Spanish:
            return "Bad signing key: \(details)"
        case .German:
            return "Bad signing key: \(details)"
        case .Polish:
            return "Nieprawidłowy klucz podpisujący: \(details)"
        }
    }
    // key: Chain
    public static func chain() -> String {
        switch currentLanguage {
        case .English:
            return "Chain"
        case .Spanish:
            return "Chain"
        case .German:
            return "Kette"
        case .Polish:
            return "Łańcuch"
        }
    }
    // key: Connection Timeout
    public static func connectiontimeout() -> String {
        switch currentLanguage {
        case .English:
            return "Connection Timeout"
        case .Spanish:
            return "Connection Timeout"
        case .German:
            return "Verbindung ausgelaufen"
        case .Polish:
            return "Limit czasu połączenia"
        }
    }
    // key: Connection error: {details}
    public static func connectionerrordetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Connection error: \(details)"
        case .Spanish:
            return "Connection error: \(details)"
        case .German:
            return "Connection error: \(details)"
        case .Polish:
            return "Błąd połączenia: \(details)"
        }
    }
    // key: Contribute to DNS Inspector
    public static func contributetodnsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Contribute to DNS Inspector"
        case .Spanish:
            return "Contribuir to DNS Inspector"
        case .German:
            return "Zu DNS-Inspector beitragen"
        case .Polish:
            return "Współtwórz DNS Inspector"
        }
    }
    // key: Coordinates
    public static func coordinates() -> String {
        switch currentLanguage {
        case .English:
            return "Coordinates"
        case .Spanish:
            return "Coordinates"
        case .German:
            return "Coordinates"
        case .Polish:
            return "Współrzędne"
        }
    }
    // key: Custom Server
    public static func customserver() -> String {
        switch currentLanguage {
        case .English:
            return "Custom Server"
        case .Spanish:
            return "Custom Server"
        case .German:
            return "Custom Server"
        case .Polish:
            return "Niestandardowy serwer"
        }
    }
    // key: DNS Inspector
    public static func dnsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "DNS Inspector"
        case .Spanish:
            return "DNS Inspector"
        case .German:
            return "DNS-Inspector"
        case .Polish:
            return "DNS Inspector"
        }
    }
    // key: DNS over HTTPS
    public static func dnsoverhttps() -> String {
        switch currentLanguage {
        case .English:
            return "DNS over HTTPS"
        case .Spanish:
            return "DNS over HTTPS"
        case .German:
            return "DNS over HTTPS"
        case .Polish:
            return "DNS przez HTTPS"
        }
    }
    // key: DNS over QUIC
    public static func dnsoverquic() -> String {
        switch currentLanguage {
        case .English:
            return "DNS over QUIC"
        case .Spanish:
            return "DNS over QUIC"
        case .German:
            return "DNS over QUIC"
        case .Polish:
            return "DNS przez QUIC"
        }
    }
    // key: DNS over TLS
    public static func dnsovertls() -> String {
        switch currentLanguage {
        case .English:
            return "DNS over TLS"
        case .Spanish:
            return "DNS over TLS"
        case .German:
            return "DNS over TLS"
        case .Polish:
            return "DNS przez TLS"
        }
    }
    // key: DNSSEC not enabled on this zone, no RRSIG returned.
    public static func dnssecnotenabledonthiszonenorrsigreturned() -> String {
        switch currentLanguage {
        case .English:
            return "DNSSEC not enabled on this zone, no RRSIG returned."
        case .Spanish:
            return "DNSSEC not enabled on this zone, no RRSIG returned."
        case .German:
            return "DNSSEC für diese Zone nicht aktiviert, kein RRSIG wiedergegeben."
        case .Polish:
            return "DNSSEC nie jest włączony dla tej strefy, nie zwrócono RRSIG."
        }
    }
    // key: Destination
    public static func destination() -> String {
        switch currentLanguage {
        case .English:
            return "Destination"
        case .Spanish:
            return "Destination"
        case .German:
            return "Destination"
        case .Polish:
            return "Cel"
        }
    }
    // key: Digest
    public static func digest() -> String {
        switch currentLanguage {
        case .English:
            return "Digest"
        case .Spanish:
            return "Digest"
        case .German:
            return "Verarbeiten"
        case .Polish:
            return "Skrót"
        }
    }
    // key: Digest Type
    public static func digesttype() -> String {
        switch currentLanguage {
        case .English:
            return "Digest Type"
        case .Spanish:
            return "Digest Type"
        case .German:
            return "Digest Type"
        case .Polish:
            return "Typ skrótu"
        }
    }
    // key: Dismiss
    public static func dismiss() -> String {
        switch currentLanguage {
        case .English:
            return "Dismiss"
        case .Spanish:
            return "Dismiss"
        case .German:
            return "Ignorieren"
        case .Polish:
            return "Zamknij"
        }
    }
    // key: Domain Information
    public static func domaininformation() -> String {
        switch currentLanguage {
        case .English:
            return "Domain Information"
        case .Spanish:
            return "Domain Information"
        case .German:
            return "Domain-Information"
        case .Polish:
            return "Informacje o domenie"
        }
    }
    // key: Edit Saved Server
    public static func editsavedserver() -> String {
        switch currentLanguage {
        case .English:
            return "Edit Saved Server"
        case .Spanish:
            return "Edit Saved Server"
        case .German:
            return "Edit Saved Server"
        case .Polish:
            return "Edytuj zapisany serwer"
        }
    }
    // key: Edit Saved Servers
    public static func editsavedservers() -> String {
        switch currentLanguage {
        case .English:
            return "Edit Saved Servers"
        case .Spanish:
            return "Edit Saved Servers"
        case .German:
            return "Edit Saved Servers"
        case .Polish:
            return "Edytuj zapisane serwery"
        }
    }
    // key: Empty response
    public static func emptyresponse() -> String {
        switch currentLanguage {
        case .English:
            return "Empty response"
        case .Spanish:
            return "Empty response"
        case .German:
            return "Empty response"
        case .Polish:
            return "Pusta odpowiedź"
        }
    }
    // key: Excessive response size
    public static func excessiveresponsesize() -> String {
        switch currentLanguage {
        case .English:
            return "Excessive response size"
        case .Spanish:
            return "Excessive response size"
        case .German:
            return "Excessive response size"
        case .Polish:
            return "Zbyt duży rozmiar odpowiedzi"
        }
    }
    // key: Expire
    public static func expire() -> String {
        switch currentLanguage {
        case .English:
            return "Expire"
        case .Spanish:
            return "Expire"
        case .German:
            return "Auslaufen lassen"
        case .Polish:
            return "Wygaśnięcie"
        }
    }
    // key: Follow @dns-inspector.com on Bluesky
    public static func followdnsinspectorcomonbluesky() -> String {
        switch currentLanguage {
        case .English:
            return "Follow @dns-inspector.com on Bluesky"
        case .Spanish:
            return "Follow @dns-inspector.com on Bluesky"
        case .German:
            return "Folge @dns-inspector.com auf Bluesky"
        case .Polish:
            return "Obserwuj @dns-inspector.com na Bluesky"
        }
    }
    // key: Follow @dnsinspector on Mastodon
    public static func followdnsinspectoronmastodon() -> String {
        switch currentLanguage {
        case .English:
            return "Follow @dnsinspector on Mastodon"
        case .Spanish:
            return "Sigue a @dnsinspector en Mastodon"
        case .German:
            return "Folge @dnsinspector auf Mastodon"
        case .Polish:
            return "Obserwuj @dnsinspector na Mastodon"
        }
    }
    // key: Format binary data as
    public static func formatbinarydataas() -> String {
        switch currentLanguage {
        case .English:
            return "Format binary data as"
        case .Spanish:
            return "Format binary data as"
        case .German:
            return "Format binary data as"
        case .Polish:
            return "Formatuj dane binarne jako"
        }
    }
    // key: Friendly Name
    public static func friendlyname() -> String {
        switch currentLanguage {
        case .English:
            return "Friendly Name"
        case .Spanish:
            return "Friendly Name"
        case .German:
            return "Friendly-Name"
        case .Polish:
            return "Przyjazna nazwa"
        }
    }
    // key: General
    public static func general() -> String {
        switch currentLanguage {
        case .English:
            return "General"
        case .Spanish:
            return "General"
        case .German:
            return "Allgemein"
        case .Polish:
            return "Ogólne"
        }
    }
    // key: Get Involved
    public static func getinvolved() -> String {
        switch currentLanguage {
        case .English:
            return "Get Involved"
        case .Spanish:
            return "Involucrarse"
        case .German:
            return "Werde involviert"
        case .Polish:
            return "Dołącz do projektu"
        }
    }
    // key: HTTP {code}
    public static func httpcode(code: String) -> String {
        switch currentLanguage {
        case .English:
            return "HTTP \(code)"
        case .Spanish:
            return "HTTP \(code)"
        case .German:
            return "HTTP \(code)"
        case .Polish:
            return "HTTP \(code)"
        }
    }
    // key: Hashed Next Name
    public static func hashednextname() -> String {
        switch currentLanguage {
        case .English:
            return "Hashed Next Name"
        case .Spanish:
            return "Hashed Next Name"
        case .German:
            return "Hashed Next Name"
        case .Polish:
            return "Haszowana następna nazwa"
        }
    }
    // key: Horizontal Precision
    public static func horizontalprecision() -> String {
        switch currentLanguage {
        case .English:
            return "Horizontal Precision"
        case .Spanish:
            return "Horizontal Precision"
        case .German:
            return "Horizontal Precision"
        case .Polish:
            return "Dokładność pozioma"
        }
    }
    // key: IPv4 Hints
    public static func ipv4hints() -> String {
        switch currentLanguage {
        case .English:
            return "IPv4 Hints"
        case .Spanish:
            return "IPv4 Hints"
        case .German:
            return "IPv4-Hints"
        case .Polish:
            return "Wskazówki IPv4"
        }
    }
    // key: IPv6 Hints
    public static func ipv6hints() -> String {
        switch currentLanguage {
        case .English:
            return "IPv6 Hints"
        case .Spanish:
            return "IPv6 Hints"
        case .German:
            return "IPv6-Hints"
        case .Polish:
            return "Wskazówki IPv6"
        }
    }
    // key: IconDefault
    public static func icondefault() -> String {
        switch currentLanguage {
        case .English:
            return "Default"
        case .Spanish:
            return "Default"
        case .German:
            return "Default"
        case .Polish:
            return "Domyślna"
        }
    }
    // key: IconPride
    public static func iconpride() -> String {
        switch currentLanguage {
        case .English:
            return "Pride"
        case .Spanish:
            return "Pride"
        case .German:
            return "Pride"
        case .Polish:
            return "Pride"
        }
    }
    // key: IconTrans
    public static func icontrans() -> String {
        switch currentLanguage {
        case .English:
            return "Trans"
        case .Spanish:
            return "Trans"
        case .German:
            return "Trans"
        case .Polish:
            return "Trans"
        }
    }
    // key: Internal error: {details}
    public static func internalerrordetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Internal error: \(details)"
        case .Spanish:
            return "Internal error: \(details)"
        case .German:
            return "Internal error: \(details)"
        case .Polish:
            return "Błąd wewnętrzny: \(details)"
        }
    }
    // key: Invalid URL
    public static func invalidurl() -> String {
        switch currentLanguage {
        case .English:
            return "Invalid URL"
        case .Spanish:
            return "Invalid URL"
        case .German:
            return "Invalid URL"
        case .Polish:
            return "Nieprawidłowy adres URL"
        }
    }
    // key: Invalid content type: {details}
    public static func invalidcontenttypedetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Invalid content type: \(details)"
        case .Spanish:
            return "Invalid content type: \(details)"
        case .German:
            return "Invalid content type: \(details)"
        case .Polish:
            return "Nieprawidłowy typ zawartości: \(details)"
        }
    }
    // key: Invalid data: {details}
    public static func invaliddatadetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Invalid data: \(details)"
        case .Spanish:
            return "Invalid data: \(details)"
        case .German:
            return "Invalid data: \(details)"
        case .Polish:
            return "Nieprawidłowe dane: \(details)"
        }
    }
    // key: Invalid response: {details}
    public static func invalidresponsedetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Invalid response: \(details)"
        case .Spanish:
            return "Invalid response: \(details)"
        case .German:
            return "Invalid response: \(details)"
        case .Polish:
            return "Nieprawidłowa odpowiedź: \(details)"
        }
    }
    // key: Key Usage
    public static func keyusage() -> String {
        switch currentLanguage {
        case .English:
            return "Key Usage"
        case .Spanish:
            return "Key Usage"
        case .German:
            return "Schlüssel-Gebrauch"
        case .Polish:
            return "Użycie klucza"
        }
    }
    // key: Key signing key
    public static func keysigningkey() -> String {
        switch currentLanguage {
        case .English:
            return "Key signing key"
        case .Spanish:
            return "Key signing key"
        case .German:
            return "Schlüsselsignierungsschlüssel"
        case .Polish:
            return "Klucz podpisujący klucze"
        }
    }
    // key: Key tag
    public static func keytag() -> String {
        switch currentLanguage {
        case .English:
            return "Key tag"
        case .Spanish:
            return "Key tag"
        case .German:
            return "Schlüsseletikett"
        case .Polish:
            return "Tag klucza"
        }
    }
    // key: Loading...
    public static func loading() -> String {
        switch currentLanguage {
        case .English:
            return "Loading..."
        case .Spanish:
            return "Cargando..."
        case .German:
            return "Lädt..."
        case .Polish:
            return "Ładowanie..."
        }
    }
    // key: Main name server
    public static func mainnameserver() -> String {
        switch currentLanguage {
        case .English:
            return "Main name server"
        case .Spanish:
            return "Main name server"
        case .German:
            return "Hauptnamensserver"
        case .Polish:
            return "Główny serwer nazw"
        }
    }
    // key: Maximum History Size
    public static func maximumhistorysize() -> String {
        switch currentLanguage {
        case .English:
            return "Maximum History Size"
        case .Spanish:
            return "Maximum History Size"
        case .German:
            return "Maximum History Size"
        case .Polish:
            return "Maksymalny rozmiar historii"
        }
    }
    // key: Minimum
    public static func minimum() -> String {
        switch currentLanguage {
        case .English:
            return "Minimum"
        case .Spanish:
            return "Minimum"
        case .German:
            return "Minimum"
        case .Polish:
            return "Minimum"
        }
    }
    // key: Missing data: {details}
    public static func missingdatadetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Missing data: \(details)"
        case .Spanish:
            return "Missing data: \(details)"
        case .German:
            return "Missing data: \(details)"
        case .Polish:
            return "Brak danych: \(details)"
        }
    }
    // key: Missing keys: {details}
    public static func missingkeysdetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Missing keys: \(details)"
        case .Spanish:
            return "Missing keys: \(details)"
        case .German:
            return "Missing keys: \(details)"
        case .Polish:
            return "Brak kluczy: \(details)"
        }
    }
    // key: More from the developer
    public static func morefromthedeveloper() -> String {
        switch currentLanguage {
        case .English:
            return "More from the developer"
        case .Spanish:
            return "Más apps del desarrollador"
        case .German:
            return "Weiteres vom Entwickler"
        case .Polish:
            return "Więcej od dewelopera"
        }
    }
    // key: My Server
    public static func myserver() -> String {
        switch currentLanguage {
        case .English:
            return "My Server"
        case .Spanish:
            return "My Server"
        case .German:
            return "My Server"
        case .Polish:
            return "Mój serwer"
        }
    }
    // key: Name
    public static func name() -> String {
        switch currentLanguage {
        case .English:
            return "Name"
        case .Spanish:
            return "Nombre"
        case .German:
            return "Name"
        case .Polish:
            return "Nazwa"
        }
    }
    // key: Network
    public static func network() -> String {
        switch currentLanguage {
        case .English:
            return "Network"
        case .Spanish:
            return "Red"
        case .German:
            return "Netzwerk"
        case .Polish:
            return "Sieć"
        }
    }
    // key: New Saved Server
    public static func newsavedserver() -> String {
        switch currentLanguage {
        case .English:
            return "New Saved Server"
        case .Spanish:
            return "New Saved Server"
        case .German:
            return "New Saved Server"
        case .Polish:
            return "Zapisz nowy serwer"
        }
    }
    // key: New query
    public static func newquery() -> String {
        switch currentLanguage {
        case .English:
            return "New query"
        case .Spanish:
            return "Nueva petición"
        case .German:
            return "Neue Anfrage"
        case .Polish:
            return "Nowe zapytanie"
        }
    }
    // key: Next Name
    public static func nextname() -> String {
        switch currentLanguage {
        case .English:
            return "Next Name"
        case .Spanish:
            return "Next Name"
        case .German:
            return "Next Name"
        case .Polish:
            return "Następna nazwa"
        }
    }
    // key: No default ALPN
    public static func nodefaultalpn() -> String {
        switch currentLanguage {
        case .English:
            return "No default ALPN"
        case .Spanish:
            return "No default ALPN"
        case .German:
            return "Kein standardmäßiges ALPN"
        case .Polish:
            return "Brak domyślnego ALPN"
        }
    }
    // key: No signatures: {details}
    public static func nosignaturesdetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "No signatures: \(details)"
        case .Spanish:
            return "No signatures: \(details)"
        case .German:
            return "No signatures: \(details)"
        case .Polish:
            return "Brak podpisów: \(details)"
        }
    }
    // key: Open source licenses & attributions
    public static func opensourcelicensesattributions() -> String {
        switch currentLanguage {
        case .English:
            return "Open source licenses & attributions"
        case .Spanish:
            return "Open source licenses & attributions"
        case .German:
            return "Open source licenses & attributions"
        case .Polish:
            return "Licencje open source i atrybuty"
        }
    }
    // key: Options
    public static func options() -> String {
        switch currentLanguage {
        case .English:
            return "Options"
        case .Spanish:
            return "Opciones"
        case .German:
            return "Optionen"
        case .Polish:
            return "Opcje"
        }
    }
    // key: Port
    public static func port() -> String {
        switch currentLanguage {
        case .English:
            return "Port"
        case .Spanish:
            return "Port"
        case .German:
            return "Port"
        case .Polish:
            return "Port"
        }
    }
    // key: Priority
    public static func priority() -> String {
        switch currentLanguage {
        case .English:
            return "Priority"
        case .Spanish:
            return "Priority"
        case .German:
            return "Priorität"
        case .Polish:
            return "Priorytet"
        }
    }
    // key: Provide feedback
    public static func providefeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Provide feedback"
        case .Spanish:
            return "Provide feedback"
        case .German:
            return "Feedback hinterlassen"
        case .Polish:
            return "Przekaż opinię"
        }
    }
    // key: Public key
    public static func publickey() -> String {
        switch currentLanguage {
        case .English:
            return "Public key"
        case .Spanish:
            return "Public key"
        case .German:
            return "Öffentlicher Schlüssel"
        case .Polish:
            return "Klucz publiczny"
        }
    }
    // key: Query
    public static func query() -> String {
        switch currentLanguage {
        case .English:
            return "Query"
        case .Spanish:
            return "Petición"
        case .German:
            return "Anfrage"
        case .Polish:
            return "Zapytanie"
        }
    }
    // key: Question
    public static func question() -> String {
        switch currentLanguage {
        case .English:
            return "Question"
        case .Spanish:
            return "Pregunta"
        case .German:
            return "Frage"
        case .Polish:
            return "Pytanie"
        }
    }
    // key: Rate in App Store
    public static func rateinappstore() -> String {
        switch currentLanguage {
        case .English:
            return "Rate in App Store"
        case .Spanish:
            return "Calificar en la App Store"
        case .German:
            return "Im App-Store bewerten"
        case .Polish:
            return "Oceń w App Store"
        }
    }
    // key: Recent queries
    public static func recentqueries() -> String {
        switch currentLanguage {
        case .English:
            return "Recent queries"
        case .Spanish:
            return "Peticiones recientes"
        case .German:
            return "Letzte Anfragen"
        case .Polish:
            return "Ostatnie zapytania"
        }
    }
    // key: Record Type
    public static func recordtype() -> String {
        switch currentLanguage {
        case .English:
            return "Record Type"
        case .Spanish:
            return "Record Type"
        case .German:
            return "Record Type"
        case .Polish:
            return "Typ rekordu"
        }
    }
    // key: Record Types
    public static func recordtypes() -> String {
        switch currentLanguage {
        case .English:
            return "Record Types"
        case .Spanish:
            return "Record Types"
        case .German:
            return "Record Types"
        case .Polish:
            return "Typy rekordów"
        }
    }
    // key: Refresh
    public static func refresh() -> String {
        switch currentLanguage {
        case .English:
            return "Refresh"
        case .Spanish:
            return "Refresh"
        case .German:
            return "Neu laden"
        case .Polish:
            return "Odśwież"
        }
    }
    // key: Relative
    public static func relative() -> String {
        switch currentLanguage {
        case .English:
            return "Relative"
        case .Spanish:
            return "Relativo"
        case .German:
            return "Verwandt"
        case .Polish:
            return "Względne"
        }
    }
    // key: Remember last server
    public static func rememberlastserver() -> String {
        switch currentLanguage {
        case .English:
            return "Remember last server"
        case .Spanish:
            return "Recordar último servidor"
        case .German:
            return "Letzten Server merken"
        case .Polish:
            return "Zapamiętaj ostatni serwer"
        }
    }
    // key: Remember recent queries
    public static func rememberrecentqueries() -> String {
        switch currentLanguage {
        case .English:
            return "Remember recent queries"
        case .Spanish:
            return "Recordar peticiones recientes"
        case .German:
            return "Letzte Anfragen merken"
        case .Polish:
            return "Zapamiętaj ostatnie zapytania"
        }
    }
    // key: Response
    public static func response() -> String {
        switch currentLanguage {
        case .English:
            return "Response"
        case .Spanish:
            return "Respuesta"
        case .German:
            return "Antwort"
        case .Polish:
            return "Odpowiedź"
        }
    }
    // key: Response contained no answers
    public static func responsecontainednoanswers() -> String {
        switch currentLanguage {
        case .English:
            return "Response contained no answers"
        case .Spanish:
            return "Response contained no answers"
        case .German:
            return "Response contained no answers"
        case .Polish:
            return "Nie zwrócono odpowiedzi"
        }
    }
    // key: Results
    public static func results() -> String {
        switch currentLanguage {
        case .English:
            return "Results"
        case .Spanish:
            return "Resultados"
        case .German:
            return "Resultat"
        case .Polish:
            return "Wyniki"
        }
    }
    // key: Retry
    public static func retry() -> String {
        switch currentLanguage {
        case .English:
            return "Retry"
        case .Spanish:
            return "Retry"
        case .German:
            return "Erneut versuchen"
        case .Polish:
            return "Ponów"
        }
    }
    // key: Save
    public static func save() -> String {
        switch currentLanguage {
        case .English:
            return "Save"
        case .Spanish:
            return "Guardar"
        case .German:
            return "Sichern"
        case .Polish:
            return "Zapisz"
        }
    }
    // key: Saved Server
    public static func savedserver() -> String {
        switch currentLanguage {
        case .English:
            return "Saved Server"
        case .Spanish:
            return "Saved Server"
        case .German:
            return "Saved Server"
        case .Polish:
            return "Zapisany serwer"
        }
    }
    // key: Saved Servers
    public static func savedservers() -> String {
        switch currentLanguage {
        case .English:
            return "Saved Servers"
        case .Spanish:
            return "Saved Servers"
        case .German:
            return "Saved Servers"
        case .Polish:
            return "Zapisane serwery"
        }
    }
    // key: Seconds
    public static func seconds() -> String {
        switch currentLanguage {
        case .English:
            return "Seconds"
        case .Spanish:
            return "Seconds"
        case .German:
            return "Sekunden"
        case .Polish:
            return "Sekund"
        }
    }
    // key: Send traditional DNS requests using TCP
    public static func sendtraditionaldnsrequestsusingtcp() -> String {
        switch currentLanguage {
        case .English:
            return "Send traditional DNS requests using TCP"
        case .Spanish:
            return "Enviar peticiones DNS tradicionales con TCP"
        case .German:
            return "Sende herkömmliche DNS-Anfragen mittels TCP"
        case .Polish:
            return "Wysyłaj tradycyjne zapytania DNS przez TCP"
        }
    }
    // key: Serial
    public static func serial() -> String {
        switch currentLanguage {
        case .English:
            return "Serial"
        case .Spanish:
            return "Serial"
        case .German:
            return "Serie"
        case .Polish:
            return "Numer seryjny"
        }
    }
    // key: Server
    public static func server() -> String {
        switch currentLanguage {
        case .English:
            return "Server"
        case .Spanish:
            return "Servidor"
        case .German:
            return "Server"
        case .Polish:
            return "Serwer"
        }
    }
    // key: Server Addresses
    public static func serveraddresses() -> String {
        switch currentLanguage {
        case .English:
            return "Server Addresses"
        case .Spanish:
            return "Server Addresses"
        case .German:
            return "Server Addresses"
        case .Polish:
            return "Adresy serwera"
        }
    }
    // key: Server Details
    public static func serverdetails() -> String {
        switch currentLanguage {
        case .English:
            return "Server Details"
        case .Spanish:
            return "Server Details"
        case .German:
            return "Server-Details"
        case .Polish:
            return "Szczegóły serwera"
        }
    }
    // key: Server IP
    public static func serverip() -> String {
        switch currentLanguage {
        case .English:
            return "Server IP"
        case .Spanish:
            return "IP del servidor"
        case .German:
            return "Server-IP"
        case .Polish:
            return "IP serwera"
        }
    }
    // key: Server IP Addresses (Optional)
    public static func serveripaddressesoptional() -> String {
        switch currentLanguage {
        case .English:
            return "Server IP Addresses (Optional)"
        case .Spanish:
            return "Server IP Addresses (Optional)"
        case .German:
            return "Server IP Addresses (Optional)"
        case .Polish:
            return "Adresy IP serwera (opcjonalnie)"
        }
    }
    // key: Server Type
    public static func servertype() -> String {
        switch currentLanguage {
        case .English:
            return "Server Type"
        case .Spanish:
            return "Tipo de servidor"
        case .German:
            return "Server-Typus"
        case .Polish:
            return "Typ serwera"
        }
    }
    // key: Server URL
    public static func serverurl() -> String {
        switch currentLanguage {
        case .English:
            return "Server URL"
        case .Spanish:
            return "URL del servidor"
        case .German:
            return "Server-URL"
        case .Polish:
            return "Adres URL serwera"
        }
    }
    // key: Share & Feedback
    public static func sharefeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Share & Feedback"
        case .Spanish:
            return "Compartir y comentarios"
        case .German:
            return "Teilen & Feedback"
        case .Polish:
            return "Udostępnianie i opinie"
        }
    }
    // key: Share DNS Inspector
    public static func sharednsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Share DNS Inspector"
        case .Spanish:
            return "Compartir DNS Inspector"
        case .German:
            return "DNS-Inspector teilen"
        case .Polish:
            return "Udostępnij DNS Inspector"
        }
    }
    // key: Show DNS record descriptions
    public static func showdnsrecorddescriptions() -> String {
        switch currentLanguage {
        case .English:
            return "Show DNS record descriptions"
        case .Spanish:
            return "Show DNS record descriptions"
        case .German:
            return "Beschreibungen der DNS-Aufzeichnungen anzeigen"
        case .Polish:
            return "Pokaż opisy rekordów DNS"
        }
    }
    // key: Show TTL values as
    public static func showttlvaluesas() -> String {
        switch currentLanguage {
        case .English:
            return "Show TTL values as"
        case .Spanish:
            return "Mostrar valores TTL (tiempo de vidxa) como"
        case .German:
            return "Zeige TTL-Wert als"
        case .Polish:
            return "Pokazuj wartości TTL jako"
        }
    }
    // key: Signature
    public static func signature() -> String {
        switch currentLanguage {
        case .English:
            return "Signature"
        case .Spanish:
            return "Signature"
        case .German:
            return "Signatur"
        case .Polish:
            return "Podpis"
        }
    }
    // key: Signature Validation Failed
    public static func signaturevalidationfailed() -> String {
        switch currentLanguage {
        case .English:
            return "Signature Validation Failed"
        case .Spanish:
            return "Signature Validation Failed"
        case .German:
            return "Signaturvalidierung fehlgeschlagen"
        case .Polish:
            return "Weryfikacja podpisu nie powiodła się"
        }
    }
    // key: Signature failed
    public static func signaturefailed() -> String {
        switch currentLanguage {
        case .English:
            return "Signature failed"
        case .Spanish:
            return "Signature failed"
        case .German:
            return "Signature failed"
        case .Polish:
            return "Podpis nieprawidłowy"
        }
    }
    // key: Supported Versions
    public static func supportedversions() -> String {
        switch currentLanguage {
        case .English:
            return "Supported Versions"
        case .Spanish:
            return "Supported Versions"
        case .German:
            return "Unterstütze Versionen"
        case .Polish:
            return "Obsługiwane wersje"
        }
    }
    // key: System DNS
    public static func systemdns() -> String {
        switch currentLanguage {
        case .English:
            return "System DNS"
        case .Spanish:
            return "System DNS"
        case .German:
            return "System DNS"
        case .Polish:
            return "Systemowy DNS"
        }
    }
    // key: TLS Inspector
    public static func tlsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector"
        case .Spanish:
            return "TLS Inspector"
        case .German:
            return "TLS-Inspector"
        case .Polish:
            return "TLS Inspector"
        }
    }
    // key: Target
    public static func target() -> String {
        switch currentLanguage {
        case .English:
            return "Target"
        case .Spanish:
            return "Target"
        case .German:
            return "Ziel"
        case .Polish:
            return "Cel"
        }
    }
    // key: Timed out
    public static func timedout() -> String {
        switch currentLanguage {
        case .English:
            return "Timed out"
        case .Spanish:
            return "Timed out"
        case .German:
            return "Timed out"
        case .Polish:
            return "Przekroczono limit czasu"
        }
    }
    // key: Too many redirects
    public static func toomanyredirects() -> String {
        switch currentLanguage {
        case .English:
            return "Too many redirects"
        case .Spanish:
            return "Too many redirects"
        case .German:
            return "Too many redirects"
        case .Polish:
            return "Zbyt wiele przekierowań"
        }
    }
    // key: Traditional DNS
    public static func traditionaldns() -> String {
        switch currentLanguage {
        case .English:
            return "Traditional DNS"
        case .Spanish:
            return "Traditional DNS"
        case .German:
            return "Traditional DNS"
        case .Polish:
            return "Tradycyjny DNS"
        }
    }
    // key: Trust Establishment Failed
    public static func trustestablishmentfailed() -> String {
        switch currentLanguage {
        case .English:
            return "Trust Establishment Failed"
        case .Spanish:
            return "Trust Establishment Failed"
        case .German:
            return "Vertrauensetablierung fehlgeschlagen"
        case .Polish:
            return "Nie udało się ustanowić relacji zaufania"
        }
    }
    // key: Trusted
    public static func trusted() -> String {
        switch currentLanguage {
        case .English:
            return "Trusted"
        case .Spanish:
            return "Trusted"
        case .German:
            return "Vertraut"
        case .Polish:
            return "Zaufany"
        }
    }
    // key: Unable to save your changes
    public static func unabletosaveyourchanges() -> String {
        switch currentLanguage {
        case .English:
            return "Unable to save your changes"
        case .Spanish:
            return "Unable to save your changes"
        case .German:
            return "Unable to save your changes"
        case .Polish:
            return "Nie można zapisać zmian"
        }
    }
    // key: Unexpected response: {details}
    public static func unexpectedresponsedetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Unexpected response: \(details)"
        case .Spanish:
            return "Unexpected response: \(details)"
        case .German:
            return "Unexpected response: \(details)"
        case .Polish:
            return "Nieoczekiwana odpowiedź: \(details)"
        }
    }
    // key: Unsupported algorithm
    public static func unsupportedalgorithm() -> String {
        switch currentLanguage {
        case .English:
            return "Unsupported algorithm"
        case .Spanish:
            return "Unsupported algorithm"
        case .German:
            return "Unsupported algorithm"
        case .Polish:
            return "Nieobsługiwany algorytm"
        }
    }
    // key: Untrusted
    public static func untrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Untrusted"
        case .Spanish:
            return "Untrusted"
        case .German:
            return "Misstraut"
        case .Polish:
            return "Niezaufany"
        }
    }
    // key: Untrusted root signing key
    public static func untrustedrootsigningkey() -> String {
        switch currentLanguage {
        case .English:
            return "Untrusted root signing key"
        case .Spanish:
            return "Untrusted root signing key"
        case .German:
            return "Untrusted root signing key"
        case .Polish:
            return "Niezaufany główny klucz podpisujący"
        }
    }
    // key: Unverified
    public static func unverified() -> String {
        switch currentLanguage {
        case .English:
            return "Unverified"
        case .Spanish:
            return "Unverified"
        case .German:
            return "Falsifiziert"
        case .Polish:
            return "Niezweryfikowany"
        }
    }
    // key: Use HTTP/2
    public static func usehttp2() -> String {
        switch currentLanguage {
        case .English:
            return "Use HTTP/2"
        case .Spanish:
            return "Use HTTP/2"
        case .German:
            return "Use HTTP/2"
        case .Polish:
            return "Używaj HTTP/2"
        }
    }
    // key: Use System Language
    public static func usesystemlanguage() -> String {
        switch currentLanguage {
        case .English:
            return "Use System Language"
        case .Spanish:
            return "Use System Language"
        case .German:
            return "Use System Language"
        case .Polish:
            return "Użyj języka systemowego"
        }
    }
    // key: Verbose logging
    public static func verboselogging() -> String {
        switch currentLanguage {
        case .English:
            return "Verbose logging"
        case .Spanish:
            return "Verbose logging"
        case .German:
            return "Erweitertes Protokollieren"
        case .Polish:
            return "Szczegółowe logowanie"
        }
    }
    // key: Verified
    public static func verified() -> String {
        switch currentLanguage {
        case .English:
            return "Verified"
        case .Spanish:
            return "Verified"
        case .German:
            return "Verifiziert"
        case .Polish:
            return "Zweryfikowany"
        }
    }
    // key: Version {version} (build {build})
    public static func versionversionbuildbuild(version: String, build: String) -> String {
        switch currentLanguage {
        case .English:
            return "Version \(version) (build \(build))"
        case .Spanish:
            return "Versión \(version) (compilación \(build))"
        case .German:
            return "Version \(version) (Build \(build))"
        case .Polish:
            return "Wersja \(version) (kompilacja \(build))"
        }
    }
    // key: Vertical Precision
    public static func verticalprecision() -> String {
        switch currentLanguage {
        case .English:
            return "Vertical Precision"
        case .Spanish:
            return "Vertical Precision"
        case .German:
            return "Vertical Precision"
        case .Polish:
            return "Dokładność pionowa"
        }
    }
    // key: View All
    public static func viewall() -> String {
        switch currentLanguage {
        case .English:
            return "View All"
        case .Spanish:
            return "Ver todo"
        case .German:
            return "Alle ansehen"
        case .Polish:
            return "Zobacz wszystko"
        }
    }
    // key: View DNSSEC Information
    public static func viewdnssecinformation() -> String {
        switch currentLanguage {
        case .English:
            return "View DNSSEC Information"
        case .Spanish:
            return "View DNSSEC Information"
        case .German:
            return "DNSSEC-Information anschauen"
        case .Polish:
            return "Zobacz informacje DNSSEC"
        }
    }
    // key: WHOIS not supported on this domain
    public static func whoisnotsupportedonthisdomain() -> String {
        switch currentLanguage {
        case .English:
            return "WHOIS not supported on this domain"
        case .Spanish:
            return "WHOIS not supported on this domain"
        case .German:
            return "WHOIS not supported on this domain"
        case .Polish:
            return "WHOIS nie jest obsługiwany dla tej domeny"
        }
    }
    // key: Your changes will take affect only quitting and restarting DNS Inspector
    public static func yourchangeswilltakeaffectonlyquittingandrestartingdnsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Your changes will take affect only quitting and restarting DNS Inspector"
        case .Spanish:
            return "Your changes will take affect only quitting and restarting DNS Inspector"
        case .German:
            return "Deine Änderungen werden erst nach Beenden und Neustart von DNS-Inspector wirksam"
        case .Polish:
            return "Zmiany zostaną zastosowane dopiero po zamknięciu i ponownym uruchomieniu DNS Inspector"
        }
    }
    // key: Zone signing key
    public static func zonesigningkey() -> String {
        switch currentLanguage {
        case .English:
            return "Zone signing key"
        case .Spanish:
            return "Zone signing key"
        case .German:
            return "Zonensignaturschlüssel"
        case .Polish:
            return "Klucz podpisujący strefę"
        }
    }
    // key: about_footer_{year}
    public static func aboutfooteryear(year: String) -> String {
        switch currentLanguage {
        case .English:
            return "DNS Inspector is free & libre open source software licensed under the GNU GPLv3. DNS Inspector is copyright © 2023-\(year) Ian Spence. DNS Inspector is made entirely without the use of Artificial Intelligence (AI) or Large Language Models (LLMs)."
        case .Spanish:
            return "DNS Inspector es software libre y gratuito bajo licencia GNU GPLv3. Derechos de autor de DNS Inspector © 2023-\(year) Ian Spence."
        case .German:
            return "DNS-Inspector ist eine kostenlose & freie, quelloffene Software, lizenziert unter GNU GPLv3. DNS-Inspector besitzt das Copyright © 2023-\(year) Ian Spence."
        case .Polish:
            return "DNS Inspector to darmowe i wolne oprogramowanie open source licencjonowane na warunkach GNU GPLv3. Prawa autorskie do DNS Inspector © 2023-\(year) Ian Spence. DNS Inspector jest tworzony całkowicie bez użycia Sztucznej Inteligencji (AI) ani Dużych Modeli Językowych (LLM)."
        }
    }
    // key: dns_server_doh_bootstrap
    public static func dnsserverdohbootstrap() -> String {
        switch currentLanguage {
        case .English:
            return "You can specify the IP addresses of this DNS over HTTPS server for enhanced privacy."
        case .Spanish:
            return "You can specify the IP addresses of this DNS over HTTPS server for enhanced privacy."
        case .German:
            return "You can specify the IP addresses of this DNS over HTTPS server for enhanced privacy."
        case .Polish:
            return "Możesz podać adresy IP tego serwera DNS przez HTTPS, aby zwiększyć prywatność."
        }
    }
    // key: dns_server_target_help_dns
    public static func dnsservertargethelpdns() -> String {
        switch currentLanguage {
        case .English:
            return "We connect to the DNS server using an IP address. IPv4 and IPv6 addresses are supported. To specify a port with an IPv6 address, wrap the address in square brackets. You can specify multiple IP addresses and DNS Inspector will attempt to use all of them."
        case .Spanish:
            return "We connect to the DNS server using an IP address. IPv4 and IPv6 addresses are supported. To specify a port with an IPv6 address, wrap the address in square brackets. You can specify multiple IP addresses and DNS Inspector will attempt to use all of them."
        case .German:
            return "We connect to the DNS server using an IP address. IPv4 and IPv6 addresses are supported. To specify a port with an IPv6 address, wrap the address in square brackets. You can specify multiple IP addresses and DNS Inspector will attempt to use all of them."
        case .Polish:
            return "Łączymy się z serwerem DNS przy użyciu adresu IP. Obsługiwane są adresy IPv4 i IPv6. Aby podać port dla adresu IPv6, umieść adres w nawiasach kwadratowych. Możesz podać wiele adresów IP, a DNS Inspector spróbuje użyć ich wszystkich."
        }
    }
    // key: dns_server_target_help_url
    public static func dnsservertargethelpurl() -> String {
        switch currentLanguage {
        case .English:
            return "We connect to the DNS server using a URL. Do not include the `dns` query parameter."
        case .Spanish:
            return "We connect to the DNS server using a URL. Do not include the dns query parameter."
        case .German:
            return "We connect to the DNS server using a URL. Do not include the dns query parameter."
        case .Polish:
            return "Łączymy się z serwerem DNS przy użyciu adresu URL. Nie dołączaj parametru zapytania `dns`."
        }
    }
    // key: http2_bootstrap_ip_footer
    public static func http2bootstrapipfooter() -> String {
        switch currentLanguage {
        case .English:
            return "DNS Inspector does not support HTTP/2 when one or more server IP address is defined."
        case .Spanish:
            return "DNS Inspector does not support HTTP/2 when one or more server IP address is defined."
        case .German:
            return "DNS Inspector does not support HTTP/2 when one or more server IP address is defined."
        case .Polish:
            return "DNS Inspector nie obsługuje HTTP/2, gdy zdefiniowano co najmniej jeden adres IP serwera."
        }
    }
    // key: record_description_a
    public static func recorddescriptiona() -> String {
        switch currentLanguage {
        case .English:
            return "DNS A records contain an IPv4 address."
        case .Spanish:
            return "Los registros DNS A contienen una dirección IPv4."
        case .German:
            return "DNS-A-Aufzeichnungen enthalten eine IPv4-Adresse."
        case .Polish:
            return "Rekordy DNS A zawierają adres IPv4."
        }
    }
    // key: record_description_aaaa
    public static func recorddescriptionaaaa() -> String {
        switch currentLanguage {
        case .English:
            return "DNS AAAA records contain an IPv6 address."
        case .Spanish:
            return "Los registros DNS AAAA contienen una dirección IPv6."
        case .German:
            return "DNS-AAAA-Aufzeichnungen enthalten eine IPv6-Adresse."
        case .Polish:
            return "Rekordy DNS AAAA zawierają adres IPv6."
        }
    }
    // key: record_description_cname
    public static func recorddescriptioncname() -> String {
        switch currentLanguage {
        case .English:
            return "DNS CNAME records contain destination DNS name to follow."
        case .Spanish:
            return "Los registros DNS CNAME contienen un nombre DNS al que seguir."
        case .German:
            return "DNS-CNAME-Aufzeichnungen enthalten Bestimmungs-DNS-Namen zum Verfolgen."
        case .Polish:
            return "Rekordy DNS CNAME zawierają docelową nazwę DNS do śledzenia."
        }
    }
    // key: record_description_dnskey
    public static func recorddescriptiondnskey() -> String {
        switch currentLanguage {
        case .English:
            return "DNS DNSKEY records contain cryptographic public keys used for authentication."
        case .Spanish:
            return "DNS DNSKEY records contain cryptographic public keys used for authentication."
        case .German:
            return "DNS-DNSKEY-Aufzeichnungen enthalten den kryptographischen, öffentlichen Schlüssel zur Authentifizierung."
        case .Polish:
            return "Rekordy DNS DNSKEY zawierają kryptograficzne klucze publiczne używane do uwierzytelniania."
        }
    }
    // key: record_description_ds
    public static func recorddescriptionds() -> String {
        switch currentLanguage {
        case .English:
            return "DNS DS records contain records of trusted delegation from the parent zone."
        case .Spanish:
            return "DNS DS records contain records of trusted delegation from the parent zone."
        case .German:
            return "DNS-DS-Aufzeichnungen enthalten Aufzeichnungen der vertrauten Delegation der Mutterzone."
        case .Polish:
            return "Rekordy DNS DS zawierają informacje o zaufanej delegacji ze strefy nadrzędnej."
        }
    }
    // key: record_description_https
    public static func recorddescriptionhttps() -> String {
        switch currentLanguage {
        case .English:
            return "DNS HTTPS records contain information about HTTPS web servers."
        case .Spanish:
            return "DNS HTTPS records contain information about HTTPS web servers."
        case .German:
            return "DNS-HTTPS-Aufzeichnungen enthalten Informationen über HTTPS-Web-Server."
        case .Polish:
            return "Rekordy DNS HTTPS zawierają informacje o serwerach WWW HTTPS."
        }
    }
    // key: record_description_loc
    public static func recorddescriptionloc() -> String {
        switch currentLanguage {
        case .English:
            return "DNS LOC records contain a geographical location."
        case .Spanish:
            return "DNS LOC records contain a geographical location."
        case .German:
            return "DNS LOC records contain a geographical location."
        case .Polish:
            return "Rekordy DNS LOC zawierają położenie geograficzne."
        }
    }
    // key: record_description_mx
    public static func recorddescriptionmx() -> String {
        switch currentLanguage {
        case .English:
            return "DNS MX records contain mail exchange server addresses."
        case .Spanish:
            return "Los registros DNS MX contienen direcciones de servidores de intercambio de correos electrónicos."
        case .German:
            return "DNS-MX-Aufzeichnungen enthalten E-Mail-Austausch-Server-Adressen."
        case .Polish:
            return "Rekordy DNS MX zawierają adresy serwerów wymiany poczty."
        }
    }
    // key: record_description_ns
    public static func recorddescriptionns() -> String {
        switch currentLanguage {
        case .English:
            return "DNS NS records contain the authoritative DNS server for this zone."
        case .Spanish:
            return "DNS NS records contain the authoritative DNS server for this zone."
        case .German:
            return "DNS-NS-Aufzeichnungen enthalten den authorativen DNS-Server der jeweiligen Zone."
        case .Polish:
            return "Rekordy DNS NS zawierają autorytatywny serwer DNS dla tej strefy."
        }
    }
    // key: record_description_nsec
    public static func recorddescriptionnsec() -> String {
        switch currentLanguage {
        case .English:
            return "DNS NSEC records contain security information about available records in a zone."
        case .Spanish:
            return "DNS NSEC records contain security information about available records in a zone."
        case .German:
            return "DNS NSEC records contain security information about available records in a zone."
        case .Polish:
            return "Rekordy DNS NSEC zawierają informacje bezpieczeństwa o dostępnych rekordach w strefie."
        }
    }
    // key: record_description_nsec3
    public static func recorddescriptionnsec3() -> String {
        switch currentLanguage {
        case .English:
            return "DNS NSEC3 contains security information about available records in a zone."
        case .Spanish:
            return "DNS NSEC3 contains security information about available records in a zone."
        case .German:
            return "DNS NSEC3 contains security information about available records in a zone."
        case .Polish:
            return "Rekordy DNS NSEC3 zawierają informacje bezpieczeństwa o dostępnych rekordach w strefie."
        }
    }
    // key: record_description_ptr
    public static func recorddescriptionptr() -> String {
        switch currentLanguage {
        case .English:
            return "DNS PTR records are used to resolve a domain name from an IP address."
        case .Spanish:
            return "Los registros DNS PTR se usan para resolver un dominio DNS a partir de una dirección IP."
        case .German:
            return "DNS-PTR-Aufzeichnungen werden zur Auflösung einer Domain zu einer IP-Adresse genutzt."
        case .Polish:
            return "Rekordy DNS PTR służą do rozwiązywania nazwy domeny na podstawie adresu IP."
        }
    }
    // key: record_description_soa
    public static func recorddescriptionsoa() -> String {
        switch currentLanguage {
        case .English:
            return "DNS SOA records contain administrative or ownership information about the domain."
        case .Spanish:
            return "DNS SOA records contain administrative or ownership information about the domain."
        case .German:
            return "DNS-SOA-Aufzeichnungen enhalten Administrativ- oder Inhaberschaftsinformationen der Domain."
        case .Polish:
            return "Rekordy DNS SOA zawierają informacje administracyjne lub własnościowe o domenie."
        }
    }
    // key: record_description_srv
    public static func recorddescriptionsrv() -> String {
        switch currentLanguage {
        case .English:
            return "DNS SRV records contain information for locating a specific service."
        case .Spanish:
            return "Los registros DNS SRV contienen información para localizar un servicio específico."
        case .German:
            return "DNS-SRV-Aufzeichnungen enthalten Informationen zur Ausmachung eines spezifischen Dienstes."
        case .Polish:
            return "Rekordy DNS SRV zawierają informacje potrzebne do lokalizowania konkretnej usługi."
        }
    }
    // key: record_description_txt
    public static func recorddescriptiontxt() -> String {
        switch currentLanguage {
        case .English:
            return "DNS TXT records contain any text data."
        case .Spanish:
            return "Los registros DNS TXT pueden contener texto arbitrario."
        case .German:
            return "DNS-TXT-Aufzeichnungen enthalten Textdaten."
        case .Polish:
            return "Rekordy DNS TXT zawierają dowolne dane tekstowe."
        }
    }
    // key: saved_server_footer
    public static func savedserverfooter() -> String {
        switch currentLanguage {
        case .English:
            return "DNS Inspector includes several saved servers to help you get started. Cloudflare, Google, and Quad9 are registered trademarks of their respective owners and are not affiliated with and do not endorse DNS Inspector."
        case .Spanish:
            return "DNS Inspector includes several saved servers to help you get started. Cloudflare, Google, and Quad9 are registered trademarks of their respective owners and are not affiliated with and do not endorse DNS Inspector."
        case .German:
            return "DNS Inspector includes several saved servers to help you get started. Cloudflare, Google, and Quad9 are registered trademarks of their respective owners and are not affiliated with and do not endorse DNS Inspector."
        case .Polish:
            return "DNS Inspector zawiera kilka zapisanych serwerów, które pomogą Ci zacząć. Cloudflare, Google i Quad9 są zastrzeżonymi znakami towarowymi ich właścicieli i nie są powiązane z DNS Inspector ani go nie wspierają."
        }
    }
    // key: {duration} microseconds
    public static func durationmicroseconds(duration: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(duration) microseconds"
        case .Spanish:
            return "\(duration) microsegundos"
        case .German:
            return "\(duration) Mikrosekunden"
        case .Polish:
            return "\(duration) mikrosekund"
        }
    }
    // key: {duration} milliseconds
    public static func durationmilliseconds(duration: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(duration) milliseconds"
        case .Spanish:
            return "\(duration) milisegundos"
        case .German:
            return "\(duration) Millisekunden"
        case .Polish:
            return "\(duration) milisekund"
        }
    }
    // key: {duration} nanoseconds
    public static func durationnanoseconds(duration: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(duration) nanoseconds"
        case .Spanish:
            return "\(duration) nanosegundos"
        case .German:
            return "\(duration) Nanosekunden"
        case .Polish:
            return "\(duration) nanosekund"
        }
    }
    // key: {duration} seconds
    public static func durationseconds(duration: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(duration) seconds"
        case .Spanish:
            return "\(duration) segundos"
        case .German:
            return "\(duration) Sekunden"
        case .Polish:
            return "\(duration) sekund"
        }
    }
    // key: {record_type} Record
    public static func recordtyperecord(record_type: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(record_type) Record"
        case .Spanish:
            return "Registro \(record_type)"
        case .German:
            return "\(record_type)-Aufzeichnung"
        case .Polish:
            return "Rekord \(record_type)"
        }
    }
}
