// DNS Inspector
// Copyright (C) Ian Spence and other DNS Inspector Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE DIRECTLY!
// This file is generated automatically using the lang.py script located in
// the same directory as this file

import Foundation

@MainActor
public enum SupportedLanguages: String, CaseIterable, Codable {
    case English = "en"
    case Spanish = "es"
    case German = "de"
}

@MainActor
public var currentLanguage: SupportedLanguages = .English

@MainActor
public final class Localize {
    // key: About
    static func about() -> String {
        switch currentLanguage {
        case .English:
            return "About"
        case .Spanish:
            return "Acerca de"
        case .German:
            return "Über"
        }
    }
    // key: Absolute
    static func absolute() -> String {
        switch currentLanguage {
        case .English:
            return "Absolute"
        case .Spanish:
            return "Absoluto"
        case .German:
            return "Absolut"
        }
    }
    // key: Add Preset Server
    static func addpresetserver() -> String {
        switch currentLanguage {
        case .English:
            return "Add Preset Server"
        case .Spanish:
            return "Añadir servidor predefinido"
        case .German:
            return "Preset-Server hinzufügen"
        }
    }
    // key: Administrative address
    static func administrativeaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Administrative address"
        case .Spanish:
            return "Administrative address"
        case .German:
            return "Administrative Adresse"
        }
    }
    // key: Algorithm
    static func algorithm() -> String {
        switch currentLanguage {
        case .English:
            return "Algorithm"
        case .Spanish:
            return "Algorithm"
        case .German:
            return "Algorithmus"
        }
    }
    // key: Altitude
    static func altitude() -> String {
        switch currentLanguage {
        case .English:
            return "Altitude"
        case .Spanish:
            return "Altitude"
        case .German:
            return "Altitude"
        }
    }
    // key: Answers
    static func answers() -> String {
        switch currentLanguage {
        case .English:
            return "Answers"
        case .Spanish:
            return "Respuestas"
        case .German:
            return "Antworten"
        }
    }
    // key: App Icon
    static func appicon() -> String {
        switch currentLanguage {
        case .English:
            return "App Icon"
        case .Spanish:
            return "App Icon"
        case .German:
            return "App Icon"
        }
    }
    // key: App language
    static func applanguage() -> String {
        switch currentLanguage {
        case .English:
            return "App language"
        case .Spanish:
            return "App language"
        case .German:
            return "App-Sprache"
        }
    }
    // key: AppIconFooter
    static func appiconfooter() -> String {
        switch currentLanguage {
        case .English:
            return "The \"Progress\" pride flag was created by Daniel Quasar and is licensed under Create Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        case .Spanish:
            return "The \"Progress\" pride flag was created by Daniel Quasar and is licensed under Create Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        case .German:
            return "The \"Progress\" pride flag was created by Daniel Quasar and is licensed under Create Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        }
    }
    // key: Appearance & Behaviour
    static func appearancebehaviour() -> String {
        switch currentLanguage {
        case .English:
            return "Appearance & Behaviour"
        case .Spanish:
            return "Appearance & Behaviour"
        case .German:
            return "Aussehen & Verhalten"
        }
    }
    // key: Area
    static func area() -> String {
        switch currentLanguage {
        case .English:
            return "Area"
        case .Spanish:
            return "Area"
        case .German:
            return "Area"
        }
    }
    // key: Automatically
    static func automatically() -> String {
        switch currentLanguage {
        case .English:
            return "Automatically"
        case .Spanish:
            return "Automatically"
        case .German:
            return "Automatisch"
        }
    }
    // key: Bad signing key: {details}
    static func badsigningkeydetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Bad signing key: \(details)"
        case .Spanish:
            return "Bad signing key: \(details)"
        case .German:
            return "Bad signing key: \(details)"
        }
    }
    // key: Chain
    static func chain() -> String {
        switch currentLanguage {
        case .English:
            return "Chain"
        case .Spanish:
            return "Chain"
        case .German:
            return "Kette"
        }
    }
    // key: Connection Timeout
    static func connectiontimeout() -> String {
        switch currentLanguage {
        case .English:
            return "Connection Timeout"
        case .Spanish:
            return "Connection Timeout"
        case .German:
            return "Verbindung ausgelaufen"
        }
    }
    // key: Connection error: {details}
    static func connectionerrordetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Connection error: \(details)"
        case .Spanish:
            return "Connection error: \(details)"
        case .German:
            return "Connection error: \(details)"
        }
    }
    // key: Contribute to DNS Inspector
    static func contributetodnsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Contribute to DNS Inspector"
        case .Spanish:
            return "Contribuir to DNS Inspector"
        case .German:
            return "Zu DNS-Inspector beitragen"
        }
    }
    // key: Coordinates
    static func coordinates() -> String {
        switch currentLanguage {
        case .English:
            return "Coordinates"
        case .Spanish:
            return "Coordinates"
        case .German:
            return "Coordinates"
        }
    }
    // key: DNS Inspector
    static func dnsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "DNS Inspector"
        case .Spanish:
            return "DNS Inspector"
        case .German:
            return "DNS-Inspector"
        }
    }
    // key: DNSSEC Enabled
    static func dnssecenabled() -> String {
        switch currentLanguage {
        case .English:
            return "DNSSEC Enabled"
        case .Spanish:
            return "DNSSEC Enabled"
        case .German:
            return "DNSSEC aktiviert"
        }
    }
    // key: DNSSEC not enabled on this zone, no RRSIG returned.
    static func dnssecnotenabledonthiszonenorrsigreturned() -> String {
        switch currentLanguage {
        case .English:
            return "DNSSEC not enabled on this zone, no RRSIG returned."
        case .Spanish:
            return "DNSSEC not enabled on this zone, no RRSIG returned."
        case .German:
            return "DNSSEC für diese Zone nicht aktiviert, kein RRSIG wiedergegeben."
        }
    }
    // key: Digest
    static func digest() -> String {
        switch currentLanguage {
        case .English:
            return "Digest"
        case .Spanish:
            return "Digest"
        case .German:
            return "Verarbeiten"
        }
    }
    // key: Digest Type
    static func digesttype() -> String {
        switch currentLanguage {
        case .English:
            return "Digest Type"
        case .Spanish:
            return "Digest Type"
        case .German:
            return "Digest Type"
        }
    }
    // key: Dismiss
    static func dismiss() -> String {
        switch currentLanguage {
        case .English:
            return "Dismiss"
        case .Spanish:
            return "Dismiss"
        case .German:
            return "Ignorieren"
        }
    }
    // key: Domain Information
    static func domaininformation() -> String {
        switch currentLanguage {
        case .English:
            return "Domain Information"
        case .Spanish:
            return "Domain Information"
        case .German:
            return "Domain-Information"
        }
    }
    // key: Edit Preset Server
    static func editpresetserver() -> String {
        switch currentLanguage {
        case .English:
            return "Edit Preset Server"
        case .Spanish:
            return "Edit Preset Server"
        case .German:
            return "Preset-Server bearbeiten"
        }
    }
    // key: Empty response
    static func emptyresponse() -> String {
        switch currentLanguage {
        case .English:
            return "Empty response"
        case .Spanish:
            return "Empty response"
        case .German:
            return "Empty response"
        }
    }
    // key: Error
    static func error() -> String {
        switch currentLanguage {
        case .English:
            return "Error"
        case .Spanish:
            return "Error"
        case .German:
            return "Fehler"
        }
    }
    // key: Excessive response size
    static func excessiveresponsesize() -> String {
        switch currentLanguage {
        case .English:
            return "Excessive response size"
        case .Spanish:
            return "Excessive response size"
        case .German:
            return "Excessive response size"
        }
    }
    // key: Expire
    static func expire() -> String {
        switch currentLanguage {
        case .English:
            return "Expire"
        case .Spanish:
            return "Expire"
        case .German:
            return "Auslaufen lassen"
        }
    }
    // key: Follow @dns-inspector.com on Bluesky
    static func followdnsinspectorcomonbluesky() -> String {
        switch currentLanguage {
        case .English:
            return "Follow @dns-inspector.com on Bluesky"
        case .Spanish:
            return "Follow @dns-inspector.com on Bluesky"
        case .German:
            return "Folge @dns-inspector.com auf Bluesky"
        }
    }
    // key: Follow @dnsinspector on Mastodon
    static func followdnsinspectoronmastodon() -> String {
        switch currentLanguage {
        case .English:
            return "Follow @dnsinspector on Mastodon"
        case .Spanish:
            return "Sigue a @dnsinspector en Mastodon"
        case .German:
            return "Folge @dnsinspector auf Mastodon"
        }
    }
    // key: Friendly Name
    static func friendlyname() -> String {
        switch currentLanguage {
        case .English:
            return "Friendly Name"
        case .Spanish:
            return "Friendly Name"
        case .German:
            return "Friendly-Name"
        }
    }
    // key: General
    static func general() -> String {
        switch currentLanguage {
        case .English:
            return "General"
        case .Spanish:
            return "General"
        case .German:
            return "Allgemein"
        }
    }
    // key: Get Involved
    static func getinvolved() -> String {
        switch currentLanguage {
        case .English:
            return "Get Involved"
        case .Spanish:
            return "Involucrarse"
        case .German:
            return "Werde involviert"
        }
    }
    // key: HTTP {code}
    static func httpcode(code: String) -> String {
        switch currentLanguage {
        case .English:
            return "HTTP \(code)"
        case .Spanish:
            return "HTTP \(code)"
        case .German:
            return "HTTP \(code)"
        }
    }
    // key: Horizontal Precision
    static func horizontalprecision() -> String {
        switch currentLanguage {
        case .English:
            return "Horizontal Precision"
        case .Spanish:
            return "Horizontal Precision"
        case .German:
            return "Horizontal Precision"
        }
    }
    // key: IPv4 Hints
    static func ipv4hints() -> String {
        switch currentLanguage {
        case .English:
            return "IPv4 Hints"
        case .Spanish:
            return "IPv4 Hints"
        case .German:
            return "IPv4-Hints"
        }
    }
    // key: IPv6 Hints
    static func ipv6hints() -> String {
        switch currentLanguage {
        case .English:
            return "IPv6 Hints"
        case .Spanish:
            return "IPv6 Hints"
        case .German:
            return "IPv6-Hints"
        }
    }
    // key: IconDefault
    static func icondefault() -> String {
        switch currentLanguage {
        case .English:
            return "Default"
        case .Spanish:
            return "Default"
        case .German:
            return "Default"
        }
    }
    // key: IconPride
    static func iconpride() -> String {
        switch currentLanguage {
        case .English:
            return "Pride"
        case .Spanish:
            return "Pride"
        case .German:
            return "Pride"
        }
    }
    // key: IconTrans
    static func icontrans() -> String {
        switch currentLanguage {
        case .English:
            return "Trans"
        case .Spanish:
            return "Trans"
        case .German:
            return "Trans"
        }
    }
    // key: Internal error: {details}
    static func internalerrordetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Internal error: \(details)"
        case .Spanish:
            return "Internal error: \(details)"
        case .German:
            return "Internal error: \(details)"
        }
    }
    // key: Invalid URL
    static func invalidurl() -> String {
        switch currentLanguage {
        case .English:
            return "Invalid URL"
        case .Spanish:
            return "Invalid URL"
        case .German:
            return "Invalid URL"
        }
    }
    // key: Invalid content type: {details}
    static func invalidcontenttypedetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Invalid content type: \(details)"
        case .Spanish:
            return "Invalid content type: \(details)"
        case .German:
            return "Invalid content type: \(details)"
        }
    }
    // key: Invalid data: {details}
    static func invaliddatadetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Invalid data: \(details)"
        case .Spanish:
            return "Invalid data: \(details)"
        case .German:
            return "Invalid data: \(details)"
        }
    }
    // key: Invalid response: {details}
    static func invalidresponsedetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Invalid response: \(details)"
        case .Spanish:
            return "Invalid response: \(details)"
        case .German:
            return "Invalid response: \(details)"
        }
    }
    // key: Key Usage
    static func keyusage() -> String {
        switch currentLanguage {
        case .English:
            return "Key Usage"
        case .Spanish:
            return "Key Usage"
        case .German:
            return "Schlüssel-Gebrauch"
        }
    }
    // key: Key signing key
    static func keysigningkey() -> String {
        switch currentLanguage {
        case .English:
            return "Key signing key"
        case .Spanish:
            return "Key signing key"
        case .German:
            return "Schlüsselsignierungsschlüssel"
        }
    }
    // key: Key tag
    static func keytag() -> String {
        switch currentLanguage {
        case .English:
            return "Key tag"
        case .Spanish:
            return "Key tag"
        case .German:
            return "Schlüsseletikett"
        }
    }
    // key: Loading...
    static func loading() -> String {
        switch currentLanguage {
        case .English:
            return "Loading..."
        case .Spanish:
            return "Cargando..."
        case .German:
            return "Lädt..."
        }
    }
    // key: Main name server
    static func mainnameserver() -> String {
        switch currentLanguage {
        case .English:
            return "Main name server"
        case .Spanish:
            return "Main name server"
        case .German:
            return "Hauptnamensserver"
        }
    }
    // key: Manually
    static func manually() -> String {
        switch currentLanguage {
        case .English:
            return "Manually"
        case .Spanish:
            return "Manually"
        case .German:
            return "Manuell"
        }
    }
    // key: Maximum History Size
    static func maximumhistorysize() -> String {
        switch currentLanguage {
        case .English:
            return "Maximum History Size"
        case .Spanish:
            return "Maximum History Size"
        case .German:
            return "Maximum History Size"
        }
    }
    // key: Minimum
    static func minimum() -> String {
        switch currentLanguage {
        case .English:
            return "Minimum"
        case .Spanish:
            return "Minimum"
        case .German:
            return "Minimum"
        }
    }
    // key: Missing data: {details}
    static func missingdatadetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Missing data: \(details)"
        case .Spanish:
            return "Missing data: \(details)"
        case .German:
            return "Missing data: \(details)"
        }
    }
    // key: Missing keys: {details}
    static func missingkeysdetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Missing keys: \(details)"
        case .Spanish:
            return "Missing keys: \(details)"
        case .German:
            return "Missing keys: \(details)"
        }
    }
    // key: More from the developer
    static func morefromthedeveloper() -> String {
        switch currentLanguage {
        case .English:
            return "More from the developer"
        case .Spanish:
            return "Más apps del desarrollador"
        case .German:
            return "Weiteres vom Entwickler"
        }
    }
    // key: Name
    static func name() -> String {
        switch currentLanguage {
        case .English:
            return "Name"
        case .Spanish:
            return "Nombre"
        case .German:
            return "Name"
        }
    }
    // key: Network
    static func network() -> String {
        switch currentLanguage {
        case .English:
            return "Network"
        case .Spanish:
            return "Red"
        case .German:
            return "Netzwerk"
        }
    }
    // key: New Preset Server
    static func newpresetserver() -> String {
        switch currentLanguage {
        case .English:
            return "New Preset Server"
        case .Spanish:
            return "Nuevo servidor predefinido"
        case .German:
            return "Neuer Preset-Server"
        }
    }
    // key: New query
    static func newquery() -> String {
        switch currentLanguage {
        case .English:
            return "New query"
        case .Spanish:
            return "Nueva petición"
        case .German:
            return "Neue Anfrage"
        }
    }
    // key: No default ALPN
    static func nodefaultalpn() -> String {
        switch currentLanguage {
        case .English:
            return "No default ALPN"
        case .Spanish:
            return "No default ALPN"
        case .German:
            return "Kein standardmäßiges ALPN"
        }
    }
    // key: No signatures: {details}
    static func nosignaturesdetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "No signatures: \(details)"
        case .Spanish:
            return "No signatures: \(details)"
        case .German:
            return "No signatures: \(details)"
        }
    }
    // key: Options
    static func options() -> String {
        switch currentLanguage {
        case .English:
            return "Options"
        case .Spanish:
            return "Opciones"
        case .German:
            return "Optionen"
        }
    }
    // key: Perform Validation
    static func performvalidation() -> String {
        switch currentLanguage {
        case .English:
            return "Perform Validation"
        case .Spanish:
            return "Perform Validation"
        case .German:
            return "Validierung durchführen"
        }
    }
    // key: Port
    static func port() -> String {
        switch currentLanguage {
        case .English:
            return "Port"
        case .Spanish:
            return "Port"
        case .German:
            return "Port"
        }
    }
    // key: Preset Servers
    static func presetservers() -> String {
        switch currentLanguage {
        case .English:
            return "Preset Servers"
        case .Spanish:
            return "Servidores predefinidos"
        case .German:
            return "Preset-Server"
        }
    }
    // key: Priority
    static func priority() -> String {
        switch currentLanguage {
        case .English:
            return "Priority"
        case .Spanish:
            return "Priority"
        case .German:
            return "Priorität"
        }
    }
    // key: Provide feedback
    static func providefeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Provide feedback"
        case .Spanish:
            return "Provide feedback"
        case .German:
            return "Feedback hinterlassen"
        }
    }
    // key: Public key
    static func publickey() -> String {
        switch currentLanguage {
        case .English:
            return "Public key"
        case .Spanish:
            return "Public key"
        case .German:
            return "Öffentlicher Schlüssel"
        }
    }
    // key: Query
    static func query() -> String {
        switch currentLanguage {
        case .English:
            return "Query"
        case .Spanish:
            return "Petición"
        case .German:
            return "Anfrage"
        }
    }
    // key: Question
    static func question() -> String {
        switch currentLanguage {
        case .English:
            return "Question"
        case .Spanish:
            return "Pregunta"
        case .German:
            return "Frage"
        }
    }
    // key: Rate in App Store
    static func rateinappstore() -> String {
        switch currentLanguage {
        case .English:
            return "Rate in App Store"
        case .Spanish:
            return "Calificar en la App Store"
        case .German:
            return "Im App-Store bewerten"
        }
    }
    // key: Recent queries
    static func recentqueries() -> String {
        switch currentLanguage {
        case .English:
            return "Recent queries"
        case .Spanish:
            return "Peticiones recientes"
        case .German:
            return "Letzte Anfragen"
        }
    }
    // key: Refresh
    static func refresh() -> String {
        switch currentLanguage {
        case .English:
            return "Refresh"
        case .Spanish:
            return "Refresh"
        case .German:
            return "Neu laden"
        }
    }
    // key: Relative
    static func relative() -> String {
        switch currentLanguage {
        case .English:
            return "Relative"
        case .Spanish:
            return "Relativo"
        case .German:
            return "Verwandt"
        }
    }
    // key: Remember last server
    static func rememberlastserver() -> String {
        switch currentLanguage {
        case .English:
            return "Remember last server"
        case .Spanish:
            return "Recordar último servidor"
        case .German:
            return "Letzten Server merken"
        }
    }
    // key: Remember recent queries
    static func rememberrecentqueries() -> String {
        switch currentLanguage {
        case .English:
            return "Remember recent queries"
        case .Spanish:
            return "Recordar peticiones recientes"
        case .German:
            return "Letzte Anfragen merken"
        }
    }
    // key: Response
    static func response() -> String {
        switch currentLanguage {
        case .English:
            return "Response"
        case .Spanish:
            return "Respuesta"
        case .German:
            return "Antwort"
        }
    }
    // key: Results
    static func results() -> String {
        switch currentLanguage {
        case .English:
            return "Results"
        case .Spanish:
            return "Resultados"
        case .German:
            return "Resultat"
        }
    }
    // key: Retry
    static func retry() -> String {
        switch currentLanguage {
        case .English:
            return "Retry"
        case .Spanish:
            return "Retry"
        case .German:
            return "Erneut versuchen"
        }
    }
    // key: Save
    static func save() -> String {
        switch currentLanguage {
        case .English:
            return "Save"
        case .Spanish:
            return "Guardar"
        case .German:
            return "Sichern"
        }
    }
    // key: Seconds
    static func seconds() -> String {
        switch currentLanguage {
        case .English:
            return "Seconds"
        case .Spanish:
            return "Seconds"
        case .German:
            return "Sekunden"
        }
    }
    // key: Send traditional DNS requests using TCP
    static func sendtraditionaldnsrequestsusingtcp() -> String {
        switch currentLanguage {
        case .English:
            return "Send traditional DNS requests using TCP"
        case .Spanish:
            return "Enviar peticiones DNS tradicionales con TCP"
        case .German:
            return "Sende herkömmliche DNS-Anfragen mittels TCP"
        }
    }
    // key: Serial
    static func serial() -> String {
        switch currentLanguage {
        case .English:
            return "Serial"
        case .Spanish:
            return "Serial"
        case .German:
            return "Serie"
        }
    }
    // key: Server
    static func server() -> String {
        switch currentLanguage {
        case .English:
            return "Server"
        case .Spanish:
            return "Servidor"
        case .German:
            return "Server"
        }
    }
    // key: Server Address
    static func serveraddress() -> String {
        switch currentLanguage {
        case .English:
            return "Server Address"
        case .Spanish:
            return "Dirección del servidor"
        case .German:
            return "Server-Adresse"
        }
    }
    // key: Server Details
    static func serverdetails() -> String {
        switch currentLanguage {
        case .English:
            return "Server Details"
        case .Spanish:
            return "Server Details"
        case .German:
            return "Server-Details"
        }
    }
    // key: Server IP
    static func serverip() -> String {
        switch currentLanguage {
        case .English:
            return "Server IP"
        case .Spanish:
            return "IP del servidor"
        case .German:
            return "Server-IP"
        }
    }
    // key: Server Type
    static func servertype() -> String {
        switch currentLanguage {
        case .English:
            return "Server Type"
        case .Spanish:
            return "Tipo de servidor"
        case .German:
            return "Server-Typus"
        }
    }
    // key: Server URL
    static func serverurl() -> String {
        switch currentLanguage {
        case .English:
            return "Server URL"
        case .Spanish:
            return "URL del servidor"
        case .German:
            return "Server-URL"
        }
    }
    // key: Share & Feedback
    static func sharefeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Share & Feedback"
        case .Spanish:
            return "Compartir y comentarios"
        case .German:
            return "Teilen & Feedback"
        }
    }
    // key: Share DNS Inspector
    static func sharednsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Share DNS Inspector"
        case .Spanish:
            return "Compartir DNS Inspector"
        case .German:
            return "DNS-Inspector teilen"
        }
    }
    // key: Show DNS record descriptions
    static func showdnsrecorddescriptions() -> String {
        switch currentLanguage {
        case .English:
            return "Show DNS record descriptions"
        case .Spanish:
            return "Show DNS record descriptions"
        case .German:
            return "Beschreibungen der DNS-Aufzeichnungen anzeigen"
        }
    }
    // key: Show TTL values as
    static func showttlvaluesas() -> String {
        switch currentLanguage {
        case .English:
            return "Show TTL values as"
        case .Spanish:
            return "Mostrar valores TTL (tiempo de vidxa) como"
        case .German:
            return "Zeige TTL-Wert als"
        }
    }
    // key: Signature
    static func signature() -> String {
        switch currentLanguage {
        case .English:
            return "Signature"
        case .Spanish:
            return "Signature"
        case .German:
            return "Signatur"
        }
    }
    // key: Signature Validation Failed
    static func signaturevalidationfailed() -> String {
        switch currentLanguage {
        case .English:
            return "Signature Validation Failed"
        case .Spanish:
            return "Signature Validation Failed"
        case .German:
            return "Signaturvalidierung fehlgeschlagen"
        }
    }
    // key: Signature failed
    static func signaturefailed() -> String {
        switch currentLanguage {
        case .English:
            return "Signature failed"
        case .Spanish:
            return "Signature failed"
        case .German:
            return "Signature failed"
        }
    }
    // key: Supported Versions
    static func supportedversions() -> String {
        switch currentLanguage {
        case .English:
            return "Supported Versions"
        case .Spanish:
            return "Supported Versions"
        case .German:
            return "Unterstütze Versionen"
        }
    }
    // key: TLS Inspector
    static func tlsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector"
        case .Spanish:
            return "TLS Inspector"
        case .German:
            return "TLS-Inspector"
        }
    }
    // key: Target
    static func target() -> String {
        switch currentLanguage {
        case .English:
            return "Target"
        case .Spanish:
            return "Target"
        case .German:
            return "Ziel"
        }
    }
    // key: Timed out
    static func timedout() -> String {
        switch currentLanguage {
        case .English:
            return "Timed out"
        case .Spanish:
            return "Timed out"
        case .German:
            return "Timed out"
        }
    }
    // key: Too many redirects
    static func toomanyredirects() -> String {
        switch currentLanguage {
        case .English:
            return "Too many redirects"
        case .Spanish:
            return "Too many redirects"
        case .German:
            return "Too many redirects"
        }
    }
    // key: Trust Establishment Failed
    static func trustestablishmentfailed() -> String {
        switch currentLanguage {
        case .English:
            return "Trust Establishment Failed"
        case .Spanish:
            return "Trust Establishment Failed"
        case .German:
            return "Vertrauensetablierung fehlgeschlagen"
        }
    }
    // key: Trusted
    static func trusted() -> String {
        switch currentLanguage {
        case .English:
            return "Trusted"
        case .Spanish:
            return "Trusted"
        case .German:
            return "Vertraut"
        }
    }
    // key: Unexpected response: {details}
    static func unexpectedresponsedetails(details: String) -> String {
        switch currentLanguage {
        case .English:
            return "Unexpected response: \(details)"
        case .Spanish:
            return "Unexpected response: \(details)"
        case .German:
            return "Unexpected response: \(details)"
        }
    }
    // key: Unsupported algorithm
    static func unsupportedalgorithm() -> String {
        switch currentLanguage {
        case .English:
            return "Unsupported algorithm"
        case .Spanish:
            return "Unsupported algorithm"
        case .German:
            return "Unsupported algorithm"
        }
    }
    // key: Untrusted
    static func untrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Untrusted"
        case .Spanish:
            return "Untrusted"
        case .German:
            return "Misstraut"
        }
    }
    // key: Untrusted root signing key
    static func untrustedrootsigningkey() -> String {
        switch currentLanguage {
        case .English:
            return "Untrusted root signing key"
        case .Spanish:
            return "Untrusted root signing key"
        case .German:
            return "Untrusted root signing key"
        }
    }
    // key: Unverified
    static func unverified() -> String {
        switch currentLanguage {
        case .English:
            return "Unverified"
        case .Spanish:
            return "Unverified"
        case .German:
            return "Falsifiziert"
        }
    }
    // key: Verbose logging
    static func verboselogging() -> String {
        switch currentLanguage {
        case .English:
            return "Verbose logging"
        case .Spanish:
            return "Verbose logging"
        case .German:
            return "Erweitertes Protokollieren"
        }
    }
    // key: Verified
    static func verified() -> String {
        switch currentLanguage {
        case .English:
            return "Verified"
        case .Spanish:
            return "Verified"
        case .German:
            return "Verifiziert"
        }
    }
    // key: Version {version} (build {build})
    static func versionversionbuildbuild(version: String, build: String) -> String {
        switch currentLanguage {
        case .English:
            return "Version \(version) (build \(build))"
        case .Spanish:
            return "Versión \(version) (compilación \(build))"
        case .German:
            return "Version \(version) (Build \(build))"
        }
    }
    // key: Vertical Precision
    static func verticalprecision() -> String {
        switch currentLanguage {
        case .English:
            return "Vertical Precision"
        case .Spanish:
            return "Vertical Precision"
        case .German:
            return "Vertical Precision"
        }
    }
    // key: View All
    static func viewall() -> String {
        switch currentLanguage {
        case .English:
            return "View All"
        case .Spanish:
            return "Ver todo"
        case .German:
            return "Alle ansehen"
        }
    }
    // key: View DNSSEC Information
    static func viewdnssecinformation() -> String {
        switch currentLanguage {
        case .English:
            return "View DNSSEC Information"
        case .Spanish:
            return "View DNSSEC Information"
        case .German:
            return "DNSSEC-Information anschauen"
        }
    }
    // key: WHOIS not supported on this domain
    static func whoisnotsupportedonthisdomain() -> String {
        switch currentLanguage {
        case .English:
            return "WHOIS not supported on this domain"
        case .Spanish:
            return "WHOIS not supported on this domain"
        case .German:
            return "WHOIS not supported on this domain"
        }
    }
    // key: Your changes will take affect only quitting and restarting DNS Inspector
    static func yourchangeswilltakeaffectonlyquittingandrestartingdnsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Your changes will take affect only quitting and restarting DNS Inspector"
        case .Spanish:
            return "Your changes will take affect only quitting and restarting DNS Inspector"
        case .German:
            return "Deine Änderungen werden erst nach Beenden und Neustart von DNS-Inspector wirksam"
        }
    }
    // key: Zone signing key
    static func zonesigningkey() -> String {
        switch currentLanguage {
        case .English:
            return "Zone signing key"
        case .Spanish:
            return "Zone signing key"
        case .German:
            return "Zonensignaturschlüssel"
        }
    }
    // key: about_footer_{year}
    static func aboutfooteryear(year: String) -> String {
        switch currentLanguage {
        case .English:
            return "DNS Inspector is free & libre open source software licensed under the GNU GPLv3. DNS Inspector is copyright © 2023-\(year) Ian Spence."
        case .Spanish:
            return "DNS Inspector es software libre y gratuito bajo licencia GNU GPLv3. Derechos de autor de DNS Inspector © 2023-\(year) Ian Spence."
        case .German:
            return "DNS-Inspector ist eine kostenlose & freie, quelloffene Software, lizenziert unter GNU GPLv3. DNS-Inspector besitzt das Copyright © 2023-\(year) Ian Spence."
        }
    }
    // key: dns_server_target_help_dns
    static func dnsservertargethelpdns() -> String {
        switch currentLanguage {
        case .English:
            return "We connect to the DNS server using an IP address. IPv4 and IPv6 addresses are supported. To specify a port with an IPv6 address, wrap the address in square brackets."
        case .Spanish:
            return "We connect to the DNS server using an IP address. IPv4 and IPv6 addresses are supported. To specify a port with an IPv6 address, wrap the address in square brackets."
        case .German:
            return "We connect to the DNS server using an IP address. IPv4 and IPv6 addresses are supported. To specify a port with an IPv6 address, wrap the address in square brackets."
        }
    }
    // key: dns_server_target_help_url
    static func dnsservertargethelpurl() -> String {
        switch currentLanguage {
        case .English:
            return "We connect to the DNS server using a URL. Do not include the dns query parameter."
        case .Spanish:
            return "We connect to the DNS server using a URL. Do not include the dns query parameter."
        case .German:
            return "We connect to the DNS server using a URL. Do not include the dns query parameter."
        }
    }
    // key: dnssec_footer
    static func dnssecfooter() -> String {
        switch currentLanguage {
        case .English:
            return "When DNSSEC is enabled all DNS queries include a request for record signatures. DNSSEC verification will perform additional queries to establish trust and may take multiple seconds to complete."
        case .Spanish:
            return "When DNSSEC is enabled all DNS queries include a request for record signatures. DNSSEC verification will perform additional queries to establish trust and may take multiple seconds to complete."
        case .German:
            return "Wenn DNSSEC aktiviert ist, enthalten alle DNS-Anfragen eine Anfrage der Signaturaufzeichnung. DNSSEC-Verifizierung wird weitere Anfragen zur Vertrauensgewinnung durchführen und möglicherweise einige Sekunden zur Durchführung brauchen."
        }
    }
    // key: record_description_a
    static func recorddescriptiona() -> String {
        switch currentLanguage {
        case .English:
            return "DNS A records contain an IPv4 address."
        case .Spanish:
            return "Los registros DNS A contienen una dirección IPv4."
        case .German:
            return "DNS-A-Aufzeichnungen enthalten eine IPv4-Adresse."
        }
    }
    // key: record_description_aaaa
    static func recorddescriptionaaaa() -> String {
        switch currentLanguage {
        case .English:
            return "DNS AAAA records contain an IPv6 address."
        case .Spanish:
            return "Los registros DNS AAAA contienen una dirección IPv6."
        case .German:
            return "DNS-AAAA-Aufzeichnungen enthalten eine IPv6-Adresse."
        }
    }
    // key: record_description_apl
    static func recorddescriptionapl() -> String {
        switch currentLanguage {
        case .English:
            return "DNS APL records contain an IP address prefix list."
        case .Spanish:
            return "Los registros DNS APL contienen una lista de prefijos IP."
        case .German:
            return "DNS-APL-Aufzeichnungen enthalten eine IP-Adressen-Prefix-Liste."
        }
    }
    // key: record_description_cname
    static func recorddescriptioncname() -> String {
        switch currentLanguage {
        case .English:
            return "DNS CNAME records contain destination DNS name to follow."
        case .Spanish:
            return "Los registros DNS CNAME contienen un nombre DNS al que seguir."
        case .German:
            return "DNS-CNAME-Aufzeichnungen enthalten Bestimmungs-DNS-Namen zum Verfolgen."
        }
    }
    // key: record_description_dnskey
    static func recorddescriptiondnskey() -> String {
        switch currentLanguage {
        case .English:
            return "DNS DNSKEY records contain cryptographic public keys used for authentication."
        case .Spanish:
            return "DNS DNSKEY records contain cryptographic public keys used for authentication."
        case .German:
            return "DNS-DNSKEY-Aufzeichnungen enthalten den kryptographischen, öffentlichen Schlüssel zur Authentifizierung."
        }
    }
    // key: record_description_ds
    static func recorddescriptionds() -> String {
        switch currentLanguage {
        case .English:
            return "DNS DS records contain records of trusted delegation from the parent zone."
        case .Spanish:
            return "DNS DS records contain records of trusted delegation from the parent zone."
        case .German:
            return "DNS-DS-Aufzeichnungen enthalten Aufzeichnungen der vertrauten Delegation der Mutterzone."
        }
    }
    // key: record_description_https
    static func recorddescriptionhttps() -> String {
        switch currentLanguage {
        case .English:
            return "DNS HTTPS records contain information about HTTPS web servers."
        case .Spanish:
            return "DNS HTTPS records contain information about HTTPS web servers."
        case .German:
            return "DNS-HTTPS-Aufzeichnungen enthalten Informationen über HTTPS-Web-Server."
        }
    }
    // key: record_description_loc
    static func recorddescriptionloc() -> String {
        switch currentLanguage {
        case .English:
            return "DNS LOC records contain a geographical location."
        case .Spanish:
            return "DNS LOC records contain a geographical location."
        case .German:
            return "DNS LOC records contain a geographical location."
        }
    }
    // key: record_description_mx
    static func recorddescriptionmx() -> String {
        switch currentLanguage {
        case .English:
            return "DNS MX records contain mail exchange server addresses."
        case .Spanish:
            return "Los registros DNS MX contienen direcciones de servidores de intercambio de correos electrónicos."
        case .German:
            return "DNS-MX-Aufzeichnungen enthalten E-Mail-Austausch-Server-Adressen."
        }
    }
    // key: record_description_ns
    static func recorddescriptionns() -> String {
        switch currentLanguage {
        case .English:
            return "DNS NS records contain the authoritative DNS server for this zone."
        case .Spanish:
            return "DNS NS records contain the authoritative DNS server for this zone."
        case .German:
            return "DNS-NS-Aufzeichnungen enthalten den authorativen DNS-Server der jeweiligen Zone."
        }
    }
    // key: record_description_ptr
    static func recorddescriptionptr() -> String {
        switch currentLanguage {
        case .English:
            return "DNS PTR records are used to resolve a domain name from an IP address."
        case .Spanish:
            return "Los registros DNS PTR se usan para resolver un dominio DNS a partir de una dirección IP."
        case .German:
            return "DNS-PTR-Aufzeichnungen werden zur Auflösung einer Domain zu einer IP-Adresse genutzt."
        }
    }
    // key: record_description_soa
    static func recorddescriptionsoa() -> String {
        switch currentLanguage {
        case .English:
            return "DNS SOA records contain administrative or ownership information about the domain."
        case .Spanish:
            return "DNS SOA records contain administrative or ownership information about the domain."
        case .German:
            return "DNS-SOA-Aufzeichnungen enhalten Administrativ- oder Inhaberschaftsinformationen der Domain."
        }
    }
    // key: record_description_srv
    static func recorddescriptionsrv() -> String {
        switch currentLanguage {
        case .English:
            return "DNS SRV records contain information for locating a specific service."
        case .Spanish:
            return "Los registros DNS SRV contienen información para localizar un servicio específico."
        case .German:
            return "DNS-SRV-Aufzeichnungen enthalten Informationen zur Ausmachung eines spezifischen Dienstes."
        }
    }
    // key: record_description_txt
    static func recorddescriptiontxt() -> String {
        switch currentLanguage {
        case .English:
            return "DNS TXT records contain any text data."
        case .Spanish:
            return "Los registros DNS TXT pueden contener texto arbitrario."
        case .German:
            return "DNS-TXT-Aufzeichnungen enthalten Textdaten."
        }
    }
    // key: {duration} microseconds
    static func durationmicroseconds(duration: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(duration) microseconds"
        case .Spanish:
            return "\(duration) microsegundos"
        case .German:
            return "\(duration) Mikrosekunden"
        }
    }
    // key: {duration} milliseconds
    static func durationmilliseconds(duration: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(duration) milliseconds"
        case .Spanish:
            return "\(duration) milisegundos"
        case .German:
            return "\(duration) Millisekunden"
        }
    }
    // key: {duration} nanoseconds
    static func durationnanoseconds(duration: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(duration) nanoseconds"
        case .Spanish:
            return "\(duration) nanosegundos"
        case .German:
            return "\(duration) Nanosekunden"
        }
    }
    // key: {duration} seconds
    static func durationseconds(duration: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(duration) seconds"
        case .Spanish:
            return "\(duration) segundos"
        case .German:
            return "\(duration) Sekunden"
        }
    }
    // key: {record_type} Record
    static func recordtyperecord(record_type: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(record_type) Record"
        case .Spanish:
            return "Registro \(record_type)"
        case .German:
            return "\(record_type)-Aufzeichnung"
        }
    }
}
