name: "Build App"

on:
  push:
    paths:
      - '.github/workflows/build_app.yml'
      - 'DNSKit/**'
      - 'DNSKitTests/**'
      - 'dns-inspector/**'
      - 'dns-inspector.xcodeproj/**'
      - '.swiftlint.yml'
  pull_request:
    paths:
      - 'DNSKit/**'
      - 'DNSKitTests/**'
      - 'dns-inspector/**'
      - 'dns-inspector.xcodeproj/**'
      - '.swiftlint.yml'
  schedule:
    - cron: "16 16 */2 * *"

permissions:
  packages: read

env:
  TEST_DEVICE: "iPhone 15 Pro"

jobs:
  build:
    name: "Build App"
    runs-on: macos-13
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v4

      - name: Install Profile and Certificates
        id: install_credentials
        run: |
          echo '${{ secrets.DNS_INSPECTOR_DEVELOPMENT_PROVISIONING_PROFILE }}' > DNS_Inspector.mobileprovision.base64
          base64 -i DNS_Inspector.mobileprovision.base64 -o DNS_Inspector.mobileprovision --decode && rm DNS_Inspector.mobileprovision.base64
          mkdir -p "~/Library/MobileDevice/Provisioning Profiles/"
          mv -v DNS_Inspector.mobileprovision   "~/Library/MobileDevice/Provisioning Profiles/39db396c-128b-4a79-8c9c-8dc36f721c92.mobileprovision"
          echo '-----BEGIN CERTIFICATE-----' > dev.crt
          echo '${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE }}' >> dev.crt
          echo '-----END CERTIFICATE-----' >> dev.crt
          echo '${{ secrets.APPLE_DEVELOPMENT_PRIVATE_KEY }}' > dev.key.base64
          base64 -i dev.key.base64 -o dev.key --decode && rm dev.key.base64
          security import dev.crt -t cert -k ~/Library/Keychains/login.keychain-db -f pemseq -A
          security import dev.key -t priv -k ~/Library/Keychains/login.keychain-db -f openssl -A
          rm dev.key dev.crt
      
      - name: "Prepare Build Environment"
        id: prepare
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "DERIVEDDATA_PATH=$(xcodebuild -project dns-inspector.xcodeproj -showBuildSettings -configuration Debug 2>/dev/null | grep " BUILD_DIR = " | cut -d '=' -f2 | awk '{$1=$1};1' | sed 's%/Build/Products%%g')" >> "$GITHUB_OUTPUT"
          echo "SWIFTLINT_CACHE_KEY=swiftlint_$(gh api repos/realm/swiftlint/releases/latest --jq '.assets[] | select(.name == "portable_swiftlint.zip") | .id')" >> "$GITHUB_OUTPUT"
          sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer
          xcode-select -p

      - name: Restore Cached SwiftLint
        id: restore_swiftlint
        uses: actions/cache@v4
        with:
          key: ${{ steps.prepare.outputs.SWIFTLINT_CACHE_KEY }}
          path: |
            /Users/runner/bin/swiftlint
      
      - name: Install SwiftLint
        id: install_swiftlint
        if: ${{ steps.restore_swiftlint.outputs.cache-hit != 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p /Users/runner/bin
          SWIFTLINT_URL=$(gh api repos/realm/swiftlint/releases/latest --jq '.assets[] | select(.name == "portable_swiftlint.zip") | .browser_download_url')
          cd /Users/runner/bin
          curl -L -o swiftlint.zip "${SWIFTLINT_URL}"
          unzip swiftlint.zip
          rm swiftlint.zip LICENSE
          chmod a+x swiftlint

      - name: Generate Strings
        id: generate_strings
        run: |
          cd "dns-inspector/Localization"
          python3 lang.py

      - name: Build
        id: build
        run: |
          xcodebuild -resolvePackageDependencies -project "dns-inspector.xcodeproj"
          xcodebuild -scheme "DNSKit" -project "dns-inspector.xcodeproj" -derivedDataPath ~/derived_data -sdk iphonesimulator -destination 'platform=iOS Simulator,name=${{ env.TEST_DEVICE }}' build
          xcodebuild -scheme "DNS Inspector" -project "dns-inspector.xcodeproj" -derivedDataPath ~/derived_data -sdk iphonesimulator -destination 'platform=iOS Simulator,name=${{ env.TEST_DEVICE }}' build

      - name: Install Go
        id: install_go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache-dependency-path: DNSKit/TestServer/go.sum

      - name: Prepare Test Server
        id: testserver_prepare
        run: |
          cd DNSKit/TestServer
          echo "Compiling test server"
          CGO_ENABLED=0 go build
          echo "Generating certifiate & key"
          ./TestServer -g
          xcrun simctl boot "${{ env.TEST_DEVICE }}"
          xcrun simctl keychain "${{ env.TEST_DEVICE }}" add-root-cert ./root.crt

      - name: Start Test Server
        id: testserver_start
        shell: bash
        run: |
          cd DNSKit/TestServer
          nohup ./TestServer -c root.crt -k root.key &

      - name: Run Automated Tests
        id: certificatekit_tests
        run: |
          xcodebuild -scheme "DNSKitTests" -project "dns-inspector.xcodeproj" -derivedDataPath ~/derived_data -sdk iphonesimulator -destination 'platform=iOS Simulator,name=${{ env.TEST_DEVICE }}' test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: /Users/runner/derived_data/Logs/Test/Test-DNSKitTests-*.xcresult
