name: "Validate Localization"

on:
  push:
    paths:
      - '.github/workflows/validate_lang.yml'
      - 'dns-inspector/Localization/**'
  pull_request:
    paths:
      - 'dns-inspector/Localization/**'

permissions:
  packages: read

jobs:
  build:
    name: "Validate Localization"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #pin v4.1.2
      
      - name: Validate localization
        id: validate_localization
        run: |
          cd "dns-inspector/Localization"
          python3 lang.py
          if [[ $(git diff --stat) != '' ]]; then
            echo "::error ::Untracked changes to localization detected!"
            git status
            exit 1
          else
            echo "No untracked changes to localization detected"
          fi
