name: "Validate License"

on:
  push:
    paths:
      - '.github/workflows/validate_license.yml'
      - 'dns-inspector/**'
  pull_request:
    paths:
      - '.github/workflows/validate_license.yml'
      - 'dns-inspector/**'
  workflow_dispatch:

permissions:
  packages: read

jobs:
  validate_license:
    name: "Validate License"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false
      
      - name: Validate License Header
        id: validate_license_header
        run: |
          python3 .github/check-license.py
