name: "Validate License"

on:
  push:
    paths:
      - '.github/workflows/validate_license.yml'
      - 'dns-inspector/**'
  pull_request:
    paths:
      - '.github/workflows/validate_license.yml'
      - 'dns-inspector/**'
  workflow_dispatch:

permissions:
  packages: read

jobs:
  validate_license:
    name: "Validate License"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #pin v5.0.0
        with:
          persist-credentials: false
      
      - name: Validate License Header
        id: validate_license_header
        run: |
          python3 .github/check-license.py
